Models/Game.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Theme_20_Homework_fromEmpty.Models;

namespace Theme_20_Homework_fromEmpty
{
    public class Game
    {

        public static int defaultStartValue;
        public static int defaultStepValue;


        static Game()
        {
            defaultStartValue = 33;
            defaultStepValue = 5;
        }

        public List<User> Users { get; set; }
        //private int InitialCount;
        
        public int Id { get; set; } 

        public int MaxStep { get; set; }
        
        public int Count { get;  set; }
        
        public User CurrentUser { get => Users[currentUserID]; }
        public string CurrentUserName { get => Users[currentUserID].Name; }


        public int currentUserID { get; set; }

        public bool GameOver { get; private set; }

        public Game(int maxStep, int InitValue, params User[] user)
        {
            Count = InitValue;
            MaxStep = maxStep;
            Users = new List<User>(user);
//            Users.Add(user); 
//            AddBot();
            //if (User.Length == 1)
            //{
            //    Users.Add(BotName);
           // }
            currentUserID = 0;
 
        }

        public Game() { }
       
        //public void AddBot()
        //{
        //    Users.Add(User.GetBot());
        //}

        public void Step(int stepvalue)
        {
            if ((Count - stepvalue) >= 0)
            {

                Count -= stepvalue;
                if (Count == 0)
                {
                    GameOver = true;
                }
                
            }
        }

        public void nextUser()
        {
            if (currentUserID < Users.Count-1)
            {
                currentUserID++;
            }
            else
            {
                currentUserID = 0;
            }

        }

        public int Botstep()
        {
            int result;
            if (Count <= MaxStep-1)
                result = Count;
            else if (Count % (MaxStep-1) != 0)
            {

                result = Count - (Count / (MaxStep-1)) * (MaxStep-1) - 1;
                if (result == 0)
                    result = MaxStep - 1;
            }
            else 
                result = (new Random()).Next(1,MaxStep);
            return result;
        }
    }
}

Models/User.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Theme_20_Homework_fromEmpty.Models
{
    public class User : IEquatable<User>
    {
        public static string BotName;
        public static int BotId;

        static User()
        {
            BotName = "Bot";
            BotId = 0;
        }

        //public static User GetBot()
        //{
        //    return new User
        //    {
        //      //  Id = BotId,
        //        Name = BotName
        //    };
        //}

        public bool Equals(User other)
        {
            return this.Id == other.Id;
        }

        public User() 
        {
            Games = new List<Game>();
        }



        public int Id { get; set; }
     //   [Key]
        public string Name { get; set; }

        public List<Game> Games { get; set; }

        public void AddGame(Game game)
        {
            Games.Add(game);
        }
    }
}

Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Theme_20_Homework_fromEmpty.ContextFolder;
using Theme_20_Homework_fromEmpty.Models;

namespace Theme_20_Homework_fromEmpty
{
    public class GameController : Controller
    {
        public ILogger _logger;
    //    private IGameCenter _GameCenter;

   //     public Game game;

       // public GameController(ILogger<GameController> logger, IGameCenter GameCenter)
        public GameController(ILogger<GameController> logger)
        {
            // _GameCenter = GameCenter;
            _logger = logger;
        }




        [HttpGet]
        public IActionResult NewGame()
        {
            _logger.LogInformation($" {DateTime.UtcNow} get new Game");


            return View();
        }

  
        [HttpPost]
        public IActionResult NewGame( string startvalue, string step, string name )
        {
            DataContext dataContext = new DataContext();
            User user = dataContext.Users.SingleOrDefault(u => u.Name == name);
            if (user == null)
            {
                 user = new User() { Name = name };
                 dataContext.Users.Add(user);
            }
            User userbot = dataContext.Users.SingleOrDefault(u => u.Name == Models.User.BotName);
            if (userbot == null)
            {
                userbot = new User() { Name = Models.User.BotName };
                dataContext.Users.Add(user);
            }

            _logger.LogInformation($"startvalue : {startvalue} step : {step}");
            user.AddGame(new Game(int.Parse(step)+1, int.Parse(startvalue), user, userbot));
            dataContext.SaveChanges();
        //    _GameCenter.AddGame(new Game(int.Parse(step)+1, int.Parse(startvalue), name));
            return RedirectToAction("Index", "Game");
        }
 
        [HttpGet]
        public IActionResult Index( )
        {
            DataContext dataContext = new DataContext();





           // User user1 = dataContext.Users.Include(u => u.Games).OrderBy(u => u.Id).Last();
            User user = dataContext.Users.Where(u => u.Name != Models.User.BotName).Include(u => u.Games).ThenInclude(g => g.Users).OrderBy(u => u.Id).Last();

            Game currentGame = user.Games.Where(g => g.GameOver != true).OrderBy(e => e.Id).LastOrDefault();
            if (currentGame == null)
                return RedirectToAction("NewGame", "Game");
            if (!currentGame.GameOver)
            {
                if(currentGame.CurrentUser.Name == Models.User.BotName)
                {
                     currentGame.Step(currentGame.Botstep());
                     currentGame.nextUser();
                    dataContext.SaveChanges();
                    if (currentGame.GameOver)
                    {
                        return Redirect("~/Result/GameOver");
                    }
                       return Redirect("~/Game/Index");
                }



             ViewData["Game"] = currentGame;
            return View();

            }
            else
                return Redirect("~/Result/GameOver");
        }

        [HttpPost]
        public IActionResult Index(string nextstep)
        {

            DataContext dataContext = new DataContext();

            User user = dataContext.Users.Where(u => u.Name != Models.User.BotName).Include(u => u.Games).ThenInclude(g => g.Users).OrderBy(u => u.Id).Last();
            Game currentGame = user.Games.Where(g => g.GameOver != true).OrderBy(e => e.Id).LastOrDefault();

            currentGame.Step(int.Parse(nextstep));
            dataContext.SaveChanges();
            if (currentGame.GameOver)
                return Redirect("~/Result/WinerPage");
            currentGame.nextUser();
            dataContext.SaveChanges();
            return Redirect("~/Game/Index");
        }




    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Theme_20_Homework_fromEmpty;

namespace Theme_20_Homework_fromEmpty
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            
            return View();
            //return RedirectToAction("GameOver", "Result", new { area = "" });
            //return RedirectToAction("GameOver", "Result");
        }
    }
}

Controllers/ResultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Theme_20_Homework_fromEmpty
{
    public class ResultController : Controller
    {
        public IActionResult GameOver()
        {
            return View();
        }

        public IActionResult WinerPage()
        {
            return View();
        }
    }
}

Views/Game/Index.cshtml
@{Game game = ViewData["Game"] as Game; }

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Игровая страница</title>
    <link rel="stylesheet" href="~/css/Styles.css" />
    <meta charset="utf-8" lang="ru" />
    <style></style>
</head>
<body>
    <main>
        <div class="Container">
            <p>@game.CurrentUserName</p>
            @*<a asp-area="" asp-controller="Result" asp-action="GameOver">Результат</a>*@
            <form asp-area="" asp-controller="Game" asp-action="Index" method="post">
                <input type="range" name="nextstep" min="1" max=@(game.MaxStep-1) value=@(game.MaxStep/2) onchange="document.getElementById('stepvalue').innerHTML = this.value;" />
                <div id="stepvalue">@(game.MaxStep/2)</div>
                <input type="submit" />
            </form>
            <p>Текущий счет @(game.Count)</p>
            <div class="game-example">
                @{
                    if(game != null)
                    for (int i = 0; i < game.Count; i++)
                    {
                    <div class="game-item"></div>

                    }
                }
            </div>
        </div>
    </main>
</body>
</html>
@{
}

Views/Game/NewGame.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    <form asp-area="" asp-controller="Game" asp-action="NewGame"  method="post" class="newGame-form">
        <label>
            Значение для запуска игры
            <input type="range" name="startvalue" min="21" max="100" value=@(Game.defaultStartValue) onchange="document.getElementById('startvalue').innerHTML = this.value;"/>
            <span id="startvalue">@(Game.defaultStartValue)</span>
        </label>
        
        <label>
            Значение для шага игры
            <input type="range" name="step" min="1" max="9" value=@(Game.defaultStepValue) onchange="document.getElementById('step').innerHTML = this.value;" />
            <span id="step">@(Game.defaultStepValue)</span>
        </label>
        <input type="text" name="name" value="" placeholder="Введите имя" />
        <input type="submit" />
    </form>
}

Views/Home/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

@(Layout = null)
*@

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Добро пожаловать!</title>
  </head>
<body>
    <main>
        <div class="Container">
            <article class="home-article">Игра , в которой игроки по очереди убирают несколько палочек. выигрывает тот игрок, который возьмет палочку последним. </article>
            <p class="home-description">По умолчанию игра начинается со @Game.defaultStartValue и можно брать максимум @(Game.defaultStepValue - 1) палочки за раз. В настройках можно изменить эти значение</p>
            <div class="game-example">
                @{
                        for (int i = 0; i < Game.defaultStartValue; i++)
                        {
                            <div class="game-item-example"></div>

                        }
                }
            </div>
            <a class="link-newGame" asp-controller="Game" asp-action="NewGame">New Game</a>
        </div>
    </main>
</body>

</html>
@{
}

Views/Result/GameOver.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@


        <div class="Container">
            <h1> GAMe over</h1>
           
            <a href="/" class="link-newGame">Новая игра</a>
        </div>

@{
}

Views/Result/WinerPage.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

<body>
    <main>
        <div class="Container">
            <h1> YOU Winer!</h1>
            
            <a href="/" class="link-newGame">Новая игра</a>
        </div>
    </main>
</body>

}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    @*<title>@ViewBag.Title</title>*@
    <link rel="stylesheet" href="~/css/Styles.css" />
    <meta charset="utf-8" lang="ru" />
</head>
<body>
    <div class="Container">
        <header>
            <div>
                <h1 class="header">Игра в Палочки</h1>
            </div>
            @*<a asp-></a>*@
        </header>
        <div>
            @RenderBody()
        </div>
        <footer class="footer">
            client ip   @Context.Request.HttpContext.Connection.RemoteIpAddress
        </footer>
    </div>

</body>
</html>